spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asset_spy_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: asset_spy_auth_service_db
        format_sql: true
server:
  port: 8081
