apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: asset-spy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nastss6tx5/asset-spy-auth-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms256m"
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 320Mi
              cpu: 300m
